### ISSUE TITLE
f***kin stucked

### ISSUE THREAD

**Issue by cristianoromaldetti** [evgenkarlson/Completed___Piscine_C___of___School_42#2]
hi guys !

I'm at the piscine in Rome (Italy) and I'm going mad with the print memory (I' ve already passed the day and go on but I want to understand as much as i can)

so the question is… the subject now is a little bit different (in the example part) but the main part is the same.. 
I've two questions 'cause we having some trouble to get the .traces so we can't see why Moulinette KO'd it.

Q1 : I' ve to manage with an eventually memory address that contain an INT ?? (in the example we have text, so a "char zone"

Q2 : the subject say's that the function must return ADDR… it mean the SAME addr it get as parameter ? or the addr of the last "character" of the memory area ? (maybe the '\0' ? or the size-1nth…

can you help us to find out ? so we don't have so make changes in the code casually until we get an ok..

thanks !

**Comment by evgenkarlson** [comment]
Q2:  The function should return the address of the "character" following the last "character" printed from the memory area

**Comment by cristianoromaldetti** [comment]
Thanks!

For Q2, I think I got it, in our subject there’s an example where the function print even the final ‘\0’ of the string (00 in hex and a dot in the last column.
So (if i understood it) I’ve to return the address of ‘\0’+1 ?
Or the address of the last letter before the string terminator?
( example if the last row is like “ thanks and see you soon. “) they want the Address of the space ? ( before the “) o the address of the “ + 1?

Sorry maybe I’m a bit confused but I’m working on this for the last 1 and half days.


Q1. No the question is another; talking with a peer next to me we start thinking in what is going to happen in Moulinette will send an address (void) that point not to a string of character but instead of something else (like and int or a long).. in that case the hexadecimal conversion and the address printing function will work fine the same, not the same for the function that print the last “block” cause putchar (Or even write) will take it as a char and than it will be all non printable instead of an Int number..

In that case we are wondering to do an unsigned char cast to handle it but I think is a bit extreme for the level we are right now..
( in the new format of the piscine that we have, that exercise will come as the last one of the day C02...

Thanks a lot !

**Comment by evgenkarlson** [comment]
**Q2:** the function should return the first address of the memory area that has not yet been printed.
**Q1:** data in memory(whatever it is) will be read 1 byte at a time. The function should not think about the correctness of displaying different types of data stored in memory. The function should simply display the contents of memory by reading data from memory one byte at a time and displaying each byte of data read.

✌️

**Comment by cristianoromaldetti** [comment]
WOW, thanks man, for real..
 we' ll keep pushing, so do you
